# Generated by Django 3.2.25 on 2024-04-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring_bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_name', models.CharField(max_length=255)),
                ('vend_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('vend_gst_treat', models.CharField(blank=True, max_length=255, null=True)),
                ('vend_gst_no', models.CharField(blank=True, max_length=220, null=True)),
                ('vend_source_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('vend_billing_address', models.TextField(blank=True, null=True)),
                ('recc_bill_no', models.CharField(max_length=255)),
                ('recc_ref_no', models.IntegerField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat_every_duration', models.IntegerField(blank=True, null=True)),
                ('repeat_every_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_bill_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('credit_period', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_period_termname', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_period_days', models.IntegerField(blank=True, null=True)),
                ('cust_name', models.CharField(max_length=255, null=True)),
                ('cust_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('cust_gst_treat', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_gst_no', models.CharField(blank=True, max_length=220, null=True)),
                ('cust_place_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('cust_billing_address', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_acc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('price_list_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.FloatField(blank=True, null=True)),
                ('adjustment', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('bal', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('save', 'save'), ('draft', 'draft')], max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('template1_doc', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('credit_period_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurringcreditperiod')),
                ('customer_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.pricelist')),
                ('repeat_every_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurringrepeatevery')),
                ('vendor_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
    ]
