# Generated by Django 3.2.25 on 2024-04-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_recurring_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurr_comments',
            name='recurr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_bills'),
        ),
        migrations.AddField(
            model_name='recurritemslist',
            name='recurr_bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_bills'),
        ),
        migrations.DeleteModel(
            name='Recurr_history',
        ),
    ]
