# Generated by Django 3.2.25 on 2024-04-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_recurr_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recurr_comments',
        ),
    ]
