# Generated by Django 3.2.25 on 2024-04-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0007_credit_note_credit_note_comments_credit_note_history_credit_note_items_credit_note_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('exp_date', models.DateField(auto_now_add=True, null=True)),
                ('expense_type', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services')], max_length=50)),
                ('Expense_account', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn', models.CharField(blank=True, max_length=255, null=True)),
                ('sac', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_Method', models.CharField(max_length=10, null=True)),
                ('cheque_id', models.CharField(blank=True, max_length=50, null=True)),
                ('upi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_gst_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_gst', models.CharField(blank=True, max_length=255, null=True)),
                ('Vendor_Sourceofsupply', models.CharField(blank=True, max_length=255, null=True)),
                ('refrenceid', models.IntegerField(blank=True, null=True)),
                ('Expense_Number', models.CharField(default='', max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customeremail', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_gsttype', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_address', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_placeofsupply', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(default='Active')),
                ('activation_tag', models.CharField(default='', max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('repeatEvery', models.CharField(blank=True, max_length=255, null=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company_Staff.chart_of_accounts')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('repeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.companyrepeatevery')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='recurring_expense_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='recurring_expense_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('action', models.CharField(default='Created', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_expense')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Recurring_Expense_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_expense')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
