# Generated by Django 3.2.25 on 2024-04-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_auto_20240415_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='bills',
        ),
    ]
