# Generated by Django 3.2.25 on 2024-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_remove_debitnote_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='debitNoteaction',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], default='Created', max_length=10),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='debitNoteaction',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], default='Created', max_length=10),
        ),
    ]
