# Generated by Django 3.2.25 on 2024-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_auto_20240417_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='tax_amount_igst',
            new_name='tax_amount',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='igst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesorderhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
