# Generated by Django 3.2.25 on 2024-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_auto_20240418_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayemnt',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='account_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
