# Generated by Django 4.2.7 on 2024-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0020_eway_bill_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
