# Generated by Django 4.2.7 on 2024-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0021_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybill',
            name='hsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='sac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
